name: windows-build
on:
  workflow_dispatch: 

concurrency:
  group: "windows-build-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      BOOST_ROOT: C:\local\boost_1_82_0
    steps:
      - name: Checkout AzerothCore
        uses: actions/checkout@v3
        with:
          repository: 'mod-playerbots/azerothcore-wotlk'
          ref: 'Playerbot'
          path: 'ac'
      - name: Checkout Playerbot Module
        uses: actions/checkout@v3
        with:
          repository: 'mod-playerbots/mod-playerbots'
          #path: 'modules/mod-playerbots'
          path: ac/modules/mod-playerbots
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.13
      - name: Configure OS
        shell: bash
        working-directory: ac
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh install-deps
      - name: Build
        shell: bash
        working-directory: ac
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build
      - name: upload-artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: out-files
          path: D:/a/mod-playerbots/mod-playerbots
